### ISSUE TITLE
composer failed to install

### ISSUE THREAD

**Issue by VaN-dev** [optii/LolApiBundle#1]
added 
```
"require": {
            "opti/LolApiBundle" : "dev-master"
        },
        "repositories" : [{
          "type" : "vcs",
          "url" : "https://github.com/optii/LolApiBundle.git"
        }],
```  
as told in readme file
Composer returns : 
```
Problem 1
    - The requested package opti/lolapibundle could not be found in any version,
 there may be a typo in the package name.
```

**Comment by synackSA** [comment]
I'm having the same problem. I thought it was a typo "opti/LolApiBundle" : "dev-master" and should be "optii/LolApiBundle" : "dev-master" (double "ii"), but that didn't seem to do anything either.

**Comment by synackSA** [comment]
Fixed it, it should be "optii/lol-api"

**Comment by VaN-dev** [comment]
Ok, fix seems to work, the package is found.
Could you edit your README acordingly please ?

I can now take a look at this bundle see if it fits my needs : )

**Comment by VaN-dev** [comment]
Actually, i can't make it work. Composer did install your bundle in vendor, but adding the bundle in the Kernel with `new Opti\LolApiBundle\OptiLolApiBundle(),` returns `FatalErrorException: Error: Class 'Opti\LolApiBundle\OptiLolApiBundle' not found`. There is a real problem in your bundle with namespace. Why didn't you respect the PSR about namings ? It leads too way too many troubles to install your bundle..

**Comment by optii** [comment]
Hi sorry guys, been without internet for a while, i made the bundle quickly for a project of mine without really taking the time to respect stuff like that, ill sort all the namings out this week for ya

**Comment by optii** [comment]
Fixed with the latest version, i've updated the readme

**Comment by Kaz-** [comment]
It seems to remain some namespace issues, i've set the "optii_lol_api" block in config.yml, registered the bundle in AppKernel.php , cleared the cache and symfony  (2.3.x) is still not able to find the bundle. 

```yaml
#config.yml
optii_lol_api:
    key: my_key #(required) Your api key 
    region: euw  #(optional) The default region
    throttle: false #(optional) Activate or deactivate the throttling 
    cache: false #(optional) Activate or deactivate the caching
```

I'm getting 
```console
 [Symfony\Component\Config\Exception\FileLoaderLoadException]
  Cannot import resource "C:\wamp\www\myproject\app/config\config.yml" from "C:\wamp\www\myproject\app/config/config_dev.yml". (There is no extension able to load the configuration for "optii_lol_api" (in C:\wamp\www\myproject\app/config\config.yml). Looked for namespace "optii_lol_api", found "framework", "security","twig", "monolog", "swiftmailer", "assetic", "doctrine", "sensio_framework_extra", "fos_user", "fos_rest", "jms_serializer", "my_project_user", "my_project_front", "my_project_team", "lexik_jwt_authentication", "
  hwi_oauth", "my_project_post", "my_project_lol", "web_profiler", "sensio_distribution")
```
