### ISSUE TITLE
No extension  for "opti_lol_api"

### ISSUE THREAD

**Issue by bartolije** [optii/LolApiBundle#4]
Hello,

I am a beginner with Symfony, and trying to use your app.
I have installed it using compaser, but when I set, in my app/config/config.yml all parameters you provide in your readme (opti_lol_api: apikey, etc), seems it isn't correctly detected.

What am I doing wrong?

Thank you.

**Comment by bartolije** [comment]
Well, it have been solved using the [pull request](https://github.com/optii/LolApiBundle/pull/2).

I just got a 
> Attempted to load class "StaticApi" from namespace "Opti\LolApiBundle\Api".

Even when I try to use:

> Optii\LolApiBundle\Api\StaticApi"
> Optii\LolApiBundle\Api;

**Comment by optii** [comment]
Hi,

I've merged the the pull request fixing this bug.

**Comment by bartolije** [comment]
Hello,

Thank you a lot for you merge.
I'm still getting the error about the attemp to load from namespace.

Controller
> use Optii\LolApiBundle\Api\StaticApi;
> [ ... ]
> $static = $this->get('opti_lol_api.static');
> $champions = $static->getChampions();

**Comment by ydenizyamac** [comment]
Hi ,
I got same error today. 
<blockquote>
Attempted to load class "StaticApi" from namespace "Opti\LolApiBundle\Api".
Did you forget a "use" statement for "Optii\LolApiBundle\Api\StaticApi"? 
</blockquote>
